### ISSUE TITLE
Proxy remark no longer valid

### ISSUE THREAD

**Issue by DonMartin76** [Haufe-Lexware/Haufe-Lexware.github.io#138]
In the README.md, the remark about the Proxy is no longer valid; I would change it, but as I am in the lucky position of usually not needing the Proxy, I really can't.

Has somebody done this and could that somebody just do a short update on the Readme? Thanks!

**Comment by chludwig-haufe** [comment]
I am preparing a blog post and I already updated the proxy instructions in my fork.
(It's http://proxy.haufemg.com:8083/, btw.)

**Comment by DonMartin76** [comment]
Awesome, thanks. I just added a remark to the README, you will need to merge that in as well then. Sorry!

**Comment by SSpeights** [comment]
Yep, domain name is the way to go if you must use the proxy. I was in pretty close comminication with ICT about this two weeks ago. Looks like CL is already taking care of this....?
