### ISSUE TITLE
Rename Silicon Black Forest to Silicon Schwarzwald?

### ISSUE THREAD

**Issue by hlgr360** [Haufe-Lexware/Haufe-Lexware.github.io#66]
http://www.wiwo.de/unternehmen/it/internet-schmiede-freiburg-ist-das-silicon-schwarzwald/7991914.html
https://www.unitedplanet.com/de/news/403

What do you think, Marco?

**Comment by marc00s** [comment]
Ja, auch die neue Meetup Gruppe (Google Devs, http://www.meetup.com/de-DE/GDG-Freiburg/) referenziert Silicon Schwarzwald. 
Ich würde noch warten, bis wir generell über die URL Bescheid wissen. Dann würde ich tatsächlich nochmal gern das Design ansprechen und in dem Zuge könnte man dann auch die Umbenennung durchziehen.

**Comment by hlgr360** [comment]
Is this still relevant?
