### ISSUE TITLE
Could we have more details on the meteor on docker app blog post?

### ISSUE THREAD

**Issue by hlgr360** [Haufe-Lexware/Haufe-Lexware.github.io#71]
Hi 

I would really like to see some more details on the meteor app on docker described by the blog post in pull #70 . Could you post some snippets in the blog itself and/or open source the app as meteor sample app? Have you fed the encountered problems back to the Meteor community - I am sure they would appreciate it.

Writing something like this

> And when I say it was tricky, I mean, the support on the internet for docker and meteor was so poor. I’ve had a lot of bugs, the meteor pack for docker it wasn’t at least official, and the problems we encountered, was already posted on the internet, with a lot of troubleshooting, but, nothing for our case.

Is like showing me the fish, but not enabling me to learn more about it.

**Comment by raulfiru** [comment]
i have to get back in touch with the student. Friday was his last day. But we have the code and i can comment on the findings. Maybe i'll ask him to update the blog post

**Comment by hlgr360** [comment]
Hmm, do you have any documentation on the findings? How is 'the learning' going to be published and communicated?

**Comment by hlgr360** [comment]
Closing issue - not because we fixed it, but because it pains me to see another chance of learning wasted,
