### ISSUE TITLE
Dockerfiles in this repo

### ISSUE THREAD

**Issue by SSpeights** [Haufe-Lexware/Haufe-Lexware.github.io#85]
Hi, I have a Dockerfile and a docker-compose.yml file that I use to spin up a jekyll container locally. This would work for anyone who has Docker. And so, I would like to:

either add the Artifacts to repo in pull request or
ignore in the .gitignore - add Dockerfile and docker-compose.yml

Which would be best?

Scott

**Comment by DonMartin76** [comment]
I would say this would totally make sense to have in the repository; we would just have to take care we don't unnecessarily publish it on the blog :-D

**Comment by hlgr360** [comment]
Made the README opinionated and removed the installation doc. Which means we can close this. Jekyll provides a default image we should be using.
